version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - proxy_network
    restart: always


  app:
    image: dogukanurker/fbdevops:latest
    expose:
      - "5000"
    networks:
      - proxy_network
    restart: always
    depends_on:
      - nginx
    build: .
    volumes:
      - ./db:/app/db

networks:
  proxy_network:
    driver: bridge

